extends Node

var FIRE_LEVEL = 1
var ORBS_PLACED = 0
var ENEMIES_KILLED = 0
var TOTAL_ENEMIES = 0
var MAX_ENEMIES = 20

func setDefaults():
	FIRE_LEVEL = 1
	ORBS_PLACED = 0
	ENEMIES_KILLED = 0
	TOTAL_ENEMIES = 0
	MAX_ENEMIES = 20
